from functools import cache

RM_WIDTH: int
RM_HEIGHT: int
INSERTED_PAGE: int

@cache
def read_meta_file(path, suffix: str = ".metadata"): ...
def is_document(path): ...
def get_document_filetype(path): ...
def get_visible_name(path): ...
def get_ui_path(path): ...
def construct_redirection_map(content: dict) -> list[int]: ...
def is_inserted_page(idx: int) -> bool: ...
def is_duplicate_page(idx: int) -> bool: ...
def get_document_tags(path: str): ...
def sanitize_obsidian_tag(tag: str) -> str: ...
def get_page_tags(path: str, page_id: str) -> list[str]: ...
def get_pages_data(path: str) -> tuple[list[str], list[int]]: ...
def list_ann_rm_files(path): ...
