from _typeshed import Incomplete
from collections.abc import Generator

__api_version__: str
timeout: int
ONE_HOUR: int
DEFAULT_NUM_ITEMS: int
DEFAULT_ITEM_LIMIT: int

def build_url(base_url, path, args_dict=None): ...
def merge_params(url, params): ...
def token(): ...
def cleanwrap(func): ...
def chunks(iterable, n) -> Generator[Incomplete]: ...
def tcache(func): ...
def backoff_check(func): ...
def retrieve(func): ...
def ss_wrap(func): ...

class Zotero:
    client: Incomplete
    endpoint: str
    local: bool
    library_id: Incomplete
    library_type: Incomplete
    api_key: Incomplete
    preserve_json_order: Incomplete
    locale: Incomplete
    url_params: Incomplete
    tag_data: bool
    request: Incomplete
    snapshot: bool
    temp_keys: Incomplete
    fmt: Incomplete
    content: Incomplete
    formats: Incomplete
    processors: Incomplete
    links: Incomplete
    self_link: Incomplete
    templates: Incomplete
    savedsearch: Incomplete
    backoff: bool
    backoff_duration: float
    def __init__(
        self,
        library_id=None,
        library_type=None,
        api_key=None,
        preserve_json_order: bool = False,
        locale: str = "en-US",
        local: bool = False,
    ) -> None: ...
    def __del__(self) -> None: ...
    @property
    def __version__(self): ...
    def default_headers(self): ...
    def add_parameters(self, **params) -> None: ...
    @retrieve
    def publications(self): ...
    def num_items(self): ...
    def count_items(self): ...
    def num_collectionitems(self, collection): ...
    @retrieve
    def key_info(self, **kwargs): ...
    @retrieve
    def items(self, **kwargs): ...
    @retrieve
    def settings(self, **kwargs): ...
    @retrieve
    def fulltext_item(self, itemkey, **kwargs): ...
    @backoff_check
    def set_fulltext(self, itemkey, payload): ...
    def new_fulltext(self, since): ...
    def item_versions(self, **kwargs): ...
    def collection_versions(self, **kwargs): ...
    def last_modified_version(self, **kwargs): ...
    @retrieve
    def top(self, **kwargs): ...
    @retrieve
    def trash(self, **kwargs): ...
    @retrieve
    def searches(self, **kwargs): ...
    @retrieve
    def deleted(self, **kwargs): ...
    @retrieve
    def item(self, item, **kwargs): ...
    @retrieve
    def file(self, item, **kwargs): ...
    def dump(self, itemkey, filename=None, path=None) -> None: ...
    @retrieve
    def children(self, item, **kwargs): ...
    @retrieve
    def collection_items(self, collection, **kwargs): ...
    @retrieve
    def collection_items_top(self, collection, **kwargs): ...
    @retrieve
    def collection_tags(self, collection, **kwargs): ...
    @retrieve
    def collection(self, collection, **kwargs): ...
    @retrieve
    def collections(self, **kwargs): ...
    def all_collections(self, collid=None): ...
    @retrieve
    def collections_top(self, **kwargs): ...
    @retrieve
    def collections_sub(self, collection, **kwargs): ...
    @retrieve
    def groups(self, **kwargs): ...
    @retrieve
    def tags(self, **kwargs): ...
    @retrieve
    def item_tags(self, item, **kwargs): ...
    def all_top(self, **kwargs): ...
    @retrieve
    def follow(self): ...
    def iterfollow(self) -> Generator[Incomplete]: ...
    def makeiter(self, func): ...
    def everything(self, query): ...
    def get_subset(self, subset): ...
    def item_template(self, itemtype, linkmode=None): ...
    @ss_wrap
    def show_operators(self): ...
    @ss_wrap
    def show_conditions(self): ...
    @ss_wrap
    def show_condition_operators(self, condition): ...
    @ss_wrap
    def saved_search(self, name, conditions): ...
    @ss_wrap
    def delete_saved_search(self, keys): ...
    def upload_attachments(self, attachments, parentid=None, basedir=None): ...
    def add_tags(self, item, *tags): ...
    def check_items(self, items): ...
    @tcache
    def item_types(self): ...
    @tcache
    def creator_fields(self): ...
    @tcache
    def item_type_fields(self, itemtype): ...
    @tcache
    def item_creator_types(self, itemtype): ...
    @tcache
    def item_fields(self): ...
    # def item_attachment_link_modes(): ...
    def create_items(self, payload, parentid=None, last_modified=None): ...
    def create_collection(self, payload, last_modified=None): ...
    def create_collections(self, payload, last_modified=None): ...
    @backoff_check
    def update_collection(self, payload, last_modified=None): ...
    def attachment_simple(self, files, parentid=None): ...
    def attachment_both(self, files, parentid=None): ...
    @backoff_check
    def update_item(self, payload, last_modified=None): ...
    def update_items(self, payload): ...
    def update_collections(self, payload): ...
    @backoff_check
    def addto_collection(self, collection, payload): ...
    @backoff_check
    def deletefrom_collection(self, collection, payload): ...
    @backoff_check
    def delete_tags(self, *payload): ...
    @backoff_check
    def delete_item(self, payload, last_modified=None): ...
    @backoff_check
    def delete_collection(self, payload, last_modified=None): ...

def error_handler(zot, req, exc=None): ...

class SavedSearch:
    zinstance: Incomplete
    searchkeys: Incomplete
    excluded_items: Incomplete
    operators: Incomplete
    groups: Incomplete
    conditions_operators: Incomplete
    def __init__(self, zinstance) -> None: ...

class Zupload:
    zinstance: Incomplete
    payload: Incomplete
    parentid: Incomplete
    basedir: Incomplete
    def __init__(self, zinstance, payload, parentid=None, basedir=None) -> None: ...
    def upload(self): ...
