class Urn:
    separate: str
    def __init__(self, path, directory: bool = False) -> None: ...
    def path(self): ...
    def quote(self): ...
    def filename(self): ...
    def parent(self): ...
    def nesting_level(self): ...
    def is_dir(self): ...
    @staticmethod
    def normalize_path(path): ...
    @staticmethod
    def compare_path(path_a, href): ...
